---
# handlers file for nifi

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart nifi
  service:
    name: nifi
    state: restarted
    enabled: yes
  when: nifi_perform_restart

- name: Reboot machine
  reboot:
    reboot_timeout: 600